Repository mulesoft-consulting/terraform-provider-anypoint, pull requests merged in 2022-06, with the labels that each got.

#45 Fix/39 dlb certificates issue after initial apply
  .gitignore
  anypoint/data_source_dlb.go
  anypoint/data_source_dlbs.go
  anypoint/resource_dlb.go
  anypoint/util.go
  docs/data-sources/dlb.md
  docs/data-sources/dlbs.md
  docs/resources/dlb.md
  go.mod
  go.sum
Labels: bug, enhancement

#47 Revert 45 fix/39 dlb certificates issue after initial apply
  anypoint/data_source_dlb.go
  anypoint/data_source_dlbs.go
  anypoint/resource_dlb.go
  anypoint/util.go
  docs/data-sources/dlb.md
  docs/data-sources/dlbs.md
  docs/resources/dlb.md
  go.mod
  go.sum
Labels: enhancement

#48 Revert "Fix/39 dlb certificates issue after initial apply"
  .gitignore
  anypoint/data_source_dlb.go
  anypoint/data_source_dlbs.go
  anypoint/resource_dlb.go
  anypoint/util.go
  docs/data-sources/dlb.md
  docs/data-sources/dlbs.md
  docs/resources/dlb.md
  go.mod
  go.sum
Labels: invalid

#51 Fix/39 dlb certificates issue after initial apply
  .gitignore
  anypoint/resource_dlb.go
  anypoint/util.go
Labels: enhancement

#52 Fix/46 org entitlement diffing customization
  anypoint/resource_bg.go
  anypoint/util.go
Labels: enhancement

#57 Creation of VPN works, reading + handling state does not.
  anypoint/data_source_vpn.go
  anypoint/provider.go
  anypoint/resource_vpn.go
  examples/data-sources/anypoint_vpn/data-source.tf
  examples/resources/anypoint_vpn/resource.tf
  examples/resources/anypoint_vpn/test.auto.tfvars
  examples/resources/anypoint_vpn/test.tf
  go.mod
  go.sum
Labels: bug, enhancement
